// 500+ FLASHCARDS — AP CSP Complete Study Set
const FLASHCARDS = [
  // ============================================================
  // BIG IDEA 1: CREATIVE DEVELOPMENT (CRD) — 100 cards
  // ============================================================
  {id:1,bi:1,front:"What is a Computational Artifact?",back:"Anything created using a computer: videos, audio, images, programs, presentations, web pages. Created by using, modifying, or combining existing artifacts."},
  {id:2,bi:1,front:"What is Iterative Development?",back:"A process of repeatedly designing, testing, and refining a program. Each iteration involves testing, finding errors, and improving based on feedback."},
  {id:3,bi:1,front:"What is Pair Programming?",back:"Two programmers share one workstation. One writes code (driver), the other reviews (navigator). Roles switch regularly. Catches errors early."},
  {id:4,bi:1,front:"What is Program Documentation?",back:"Text that explains what code does and why. Helps collaborators understand code, makes debugging easier. Written in comments inside programs."},
  {id:5,bi:1,front:"What is a Syntax Error?",back:"An error preventing a program from running because the code doesn't follow the programming language's rules (e.g., missing parentheses, misspelled keyword)."},
  {id:6,bi:1,front:"What is a Logic Error?",back:"An error where the program runs but produces incorrect output. The code follows syntax rules but the algorithm or programmer's reasoning is flawed."},
  {id:7,bi:1,front:"What is a Runtime Error?",back:"An error that occurs while the program is running, causing it to crash (e.g., dividing by zero, accessing an out-of-bounds list index)."},
  {id:8,bi:1,front:"What is Program Testing?",back:"Running a program with different inputs to verify correct outputs and find bugs before deployment."},
  {id:9,bi:1,front:"What is the difference between a driver and navigator in pair programming?",back:"Driver: types the code. Navigator: reviews the code, spots errors, thinks strategically. Roles swap regularly."},
  {id:10,bi:1,front:"Why is collaboration valuable in programming?",back:"Diverse perspectives reduce bias, catch more errors, improve design quality, and produce better programs than individuals working alone."},
  {id:11,bi:1,front:"What is Program Purpose?",back:"The problem a program is intended to solve or the creative idea it expresses."},
  {id:12,bi:1,front:"What is Program Function?",back:"How a program actually behaves when executed — what it does with inputs to produce outputs."},
  {id:13,bi:1,front:"What is an Input to a program?",back:"Data sent to a program: keyboard, mouse, microphone, camera, files, sensors, other programs."},
  {id:14,bi:1,front:"What is an Output from a program?",back:"Data sent from a program: to screen, speakers, files, other programs, devices."},
  {id:15,bi:1,front:"What is Event-Driven Programming?",back:"Programming paradigm where code runs in response to events (clicks, keystrokes, network messages) rather than sequentially from top to bottom."},
  {id:16,bi:1,front:"What is an Event Handler?",back:"A block of code that runs when a specific event occurs (e.g., when a button is clicked or a key is pressed)."},
  {id:17,bi:1,front:"What does 'incremental' mean in software development?",back:"Adding features gradually, in small pieces, building the program step-by-step rather than all at once."},
  {id:18,bi:1,front:"What is a Test Case?",back:"A specific input paired with its expected output, used to verify a program works correctly."},
  {id:19,bi:1,front:"What is an Edge Case?",back:"An extreme or unusual input value used in testing (empty input, zero, maximum value, negative number)."},
  {id:20,bi:1,front:"What is Hand Tracing?",back:"Manually executing code step-by-step on paper to find logic errors without running the program."},
  {id:21,bi:1,front:"What is a Debugger?",back:"A tool that lets programmers pause program execution at any point and examine variable values to find errors."},
  {id:22,bi:1,front:"What is Abstraction in program design?",back:"Hiding unnecessary details so programmers can focus on higher-level problem-solving. Using a function without knowing how it works internally."},
  {id:23,bi:1,front:"What is a comment in code?",back:"Text ignored by the computer but readable by humans. Explains WHY code does something. Written with // or # in most languages."},
  {id:24,bi:1,front:"What is the Software Development Lifecycle?",back:"The phases of creating software: planning, design, implementation, testing, deployment, maintenance."},
  {id:25,bi:1,front:"What is a specification?",back:"A detailed description of what a program must do — its expected inputs, outputs, and behavior."},
  {id:26,bi:1,front:"What is code refactoring?",back:"Restructuring existing code without changing its behavior — making it cleaner, more readable, or more efficient."},
  {id:27,bi:1,front:"What is a flowchart in programming?",back:"A diagram using shapes and arrows to show the flow of a program's logic — useful for planning algorithms."},
  {id:28,bi:1,front:"What is pseudocode?",back:"An informal, human-readable description of an algorithm using plain language mixed with code-like structure. Not meant to be run by a computer."},
  {id:29,bi:1,front:"What is version control?",back:"A system that tracks changes to code over time, allowing programmers to revert to earlier versions. Example: Git."},
  {id:30,bi:1,front:"What is a README file?",back:"Documentation file that describes a project: what it does, how to install it, how to use it, and who made it."},
  {id:31,bi:1,front:"What is top-down design?",back:"Breaking a large problem into smaller sub-problems, solving each sub-problem separately, then combining solutions."},
  {id:32,bi:1,front:"What is bottom-up design?",back:"Building and testing small components first, then combining them into a larger system."},
  {id:33,bi:1,front:"What is a prototype?",back:"An early, simplified version of a program used to test ideas before building the full system."},
  {id:34,bi:1,front:"What is user testing?",back:"Having actual users try a program to find usability problems and unexpected behaviors."},
  {id:35,bi:1,front:"Why do programs fail even after testing?",back:"Testing can find bugs but cannot prove a program is bug-free. Only finite inputs can be tested but there are infinite possible inputs."},
  {id:36,bi:1,front:"What is modular programming?",back:"Writing a program as separate, independent modules (functions/procedures) that can be developed and tested individually."},
  {id:37,bi:1,front:"What is code reuse?",back:"Using existing code (your own or others') to solve new problems, saving time and reducing errors."},
  {id:38,bi:1,front:"What is a library in programming?",back:"A collection of pre-written code that programmers can import and use without writing it from scratch."},
  {id:39,bi:1,front:"What is an API?",back:"Application Programming Interface — a set of functions/rules allowing programs to interact with other programs or services."},
  {id:40,bi:1,front:"What is the AP CSP Create Performance Task?",back:"A project where students design and implement a program with a video, written response, and code. Worth 30% of the AP score."},
  {id:41,bi:1,front:"What must the Create PT program demonstrate?",back:"A list (or collection), a procedure with a parameter that affects program behavior, an algorithm with sequencing/selection/iteration, and student-developed abstraction."},
  {id:42,bi:1,front:"What is sequencing in programming?",back:"Executing statements one after another in a specific order. The most basic program structure."},
  {id:43,bi:1,front:"What is selection in programming?",back:"Making a decision based on a condition — using IF/ELSE to choose between two or more code paths."},
  {id:44,bi:1,front:"What is iteration in programming?",back:"Repeating a block of code multiple times using loops (REPEAT TIMES, REPEAT UNTIL, FOR EACH)."},
  {id:45,bi:1,front:"What is a 'block-based' programming language?",back:"A visual language where code is assembled by dragging and snapping blocks together. Examples: Scratch, Snap!"},
  {id:46,bi:1,front:"What is a 'text-based' programming language?",back:"A programming language where code is typed as text. Examples: Python, Java, JavaScript, C++."},
  {id:47,bi:1,front:"What causes a program to have 'unintended effects'?",back:"Logic errors, untested edge cases, interactions between features, or incorrect understanding of requirements."},
  {id:48,bi:1,front:"What is the difference between compiling and interpreting?",back:"Compiling translates the entire program at once before running. Interpreting translates and runs line by line."},
  {id:49,bi:1,front:"What is open-source collaboration?",back:"Many developers worldwide contributing to the same project publicly. Code is visible, modifiable, and shareable by anyone."},
  {id:50,bi:1,front:"What is a code review?",back:"A process where one or more developers examine another's code for errors, style issues, and improvement opportunities before it's merged."},
  {id:51,bi:1,front:"What is 'meaningful variable naming'?",back:"Choosing variable names that describe their purpose (e.g., 'studentAge' instead of 'x'), making code self-documenting."},
  {id:52,bi:1,front:"What is a 'stub' in programming?",back:"A placeholder function with no real implementation, used during development so code structure can be tested before logic is written."},
  {id:53,bi:1,front:"What does 'program correctness' mean?",back:"A program is correct if it produces the right output for all valid inputs as specified."},
  {id:54,bi:1,front:"What is a compiler?",back:"A program that translates source code (human-written) into machine code (executable by computer)."},
  {id:55,bi:1,front:"What is an interpreter?",back:"A program that directly executes source code line by line without translating it all first."},
  {id:56,bi:1,front:"What is 'print debugging'?",back:"Adding DISPLAY/print statements to show variable values at specific points in code, helping locate where bugs occur."},
  {id:57,bi:1,front:"What is the 'divide and conquer' strategy?",back:"Solving a complex problem by breaking it into smaller, more manageable sub-problems, solving each, then combining results."},
  {id:58,bi:1,front:"What is a merge conflict in version control?",back:"When two developers change the same part of a file and the version control system can't automatically combine the changes."},
  {id:59,bi:1,front:"What does IDE stand for?",back:"Integrated Development Environment — software combining a code editor, compiler/interpreter, and debugger in one tool."},
  {id:60,bi:1,front:"What is 'code smell'?",back:"Signs in code that suggest deeper problems: long functions, repeated code, unclear names, excessive complexity."},
  {id:61,bi:1,front:"What is a boolean flag?",back:"A boolean variable used to track program state, like whether a condition has been met (isFound = true/false)."},
  {id:62,bi:1,front:"What is defensive programming?",back:"Writing code anticipating errors and unexpected inputs, including checks and error handling to prevent crashes."},
  {id:63,bi:1,front:"What is the 'DRY' principle?",back:"Don't Repeat Yourself — avoid duplicate code by putting repeated logic into reusable functions."},
  {id:64,bi:1,front:"What is whitebox testing?",back:"Testing with knowledge of the internal code structure, designing tests to cover specific code paths."},
  {id:65,bi:1,front:"What is blackbox testing?",back:"Testing based only on inputs and expected outputs, without knowing the internal implementation."},
  {id:66,bi:1,front:"What is regression testing?",back:"Re-running tests after changes to ensure new code didn't break previously working features."},
  {id:67,bi:1,front:"What is a 'magic number' in code?",back:"A hardcoded numeric value with no explanation of its meaning. Bad practice — should be replaced with a named constant."},
  {id:68,bi:1,front:"What is error handling?",back:"Code that gracefully manages unexpected conditions (wrong input, network failure) instead of crashing."},
  {id:69,bi:1,front:"What is a 'global variable'?",back:"A variable accessible from anywhere in a program. Can cause bugs when multiple parts of code modify it unexpectedly."},
  {id:70,bi:1,front:"What is a 'local variable'?",back:"A variable only accessible within the function or block where it was created. Reduces unintended interactions."},
  {id:71,bi:1,front:"What is scope in programming?",back:"The region of code where a variable is accessible. Variables have local scope (within a function) or global scope (entire program)."},
  {id:72,bi:1,front:"What is 'spaghetti code'?",back:"Code with a complex, tangled control flow — very hard to follow, debug, or maintain. Result of poor design."},
  {id:73,bi:1,front:"What is agile development?",back:"An iterative software methodology focused on small, frequent releases, collaboration, and responding to change."},
  {id:74,bi:1,front:"What is a sprint in agile?",back:"A short, time-boxed period (usually 2 weeks) where a development team completes a set of features."},
  {id:75,bi:1,front:"What is a user story?",back:"A brief description of a feature from the user's perspective: 'As a [user], I want [feature] so that [benefit].'"},
  {id:76,bi:1,front:"What is continuous integration?",back:"Automatically testing and merging code changes as developers submit them, catching errors early."},
  {id:77,bi:1,front:"What is technical debt?",back:"Future work created by shortcuts or poor design decisions now — code that needs to be improved later."},
  {id:78,bi:1,front:"What is a software bug?",back:"A flaw in a program that causes incorrect, unexpected, or unintended behavior."},
  {id:79,bi:1,front:"What is 'rubber duck debugging'?",back:"Explaining code line-by-line to an inanimate object (or person). The act of explaining often reveals the bug."},
  {id:80,bi:1,front:"What does 'compile-time error' mean?",back:"An error detected by the compiler before the program runs — typically a syntax error."},
  {id:81,bi:1,front:"What is a 'semantic error'?",back:"Another name for a logic error — the code is syntactically valid but means something different than intended."},
  {id:82,bi:1,front:"What is 'waterfall' development?",back:"A sequential model where each phase (requirements → design → build → test → deploy) must complete before the next begins."},
  {id:83,bi:1,front:"What is 'debugging'?",back:"The process of finding and fixing errors (bugs) in a program."},
  {id:84,bi:1,front:"What is program state?",back:"The values of all variables at a specific moment during program execution."},
  {id:85,bi:1,front:"What is a breakpoint?",back:"A marker in a debugger telling it to pause execution at that line so you can inspect program state."},
  {id:86,bi:1,front:"What is 'tracing through code'?",back:"Manually following code execution step by step, tracking variable values, to understand or debug the program."},
  {id:87,bi:1,front:"What is 'off by one' error?",back:"A common logic error where a loop runs one too many or one too few times, often from wrong boundary conditions."},
  {id:88,bi:1,front:"What is an 'infinite loop'?",back:"A loop that never terminates because its condition is always true. Causes programs to hang or crash."},
  {id:89,bi:1,front:"What is 'code maintainability'?",back:"How easy it is for developers (including future you) to understand, modify, and fix code over time."},
  {id:90,bi:1,front:"What is a 'naming convention'?",back:"Rules for how to name variables, functions, and files consistently (camelCase, snake_case, PascalCase)."},
  {id:91,bi:1,front:"What is GitHub?",back:"A popular platform for hosting Git repositories, enabling collaboration, code review, and version tracking."},
  {id:92,bi:1,front:"What is a 'pull request'?",back:"A request to merge code changes from one branch into another, typically reviewed by teammates before merging."},
  {id:93,bi:1,front:"What is 'branching' in version control?",back:"Creating a copy of the codebase to develop features independently without affecting the main code."},
  {id:94,bi:1,front:"What is a 'commit' in Git?",back:"A snapshot of code changes saved to the version history with a message describing what changed."},
  {id:95,bi:1,front:"What is 'scalability' in software?",back:"A program's ability to handle increased workload (more users, more data) without significant performance degradation."},
  {id:96,bi:1,front:"What is 'code complexity'?",back:"A measure of how difficult code is to understand and maintain — more branches and nesting means higher complexity."},
  {id:97,bi:1,front:"What is 'legacy code'?",back:"Old code that is hard to understand or modify but still in use, often without good documentation or tests."},
  {id:98,bi:1,front:"What is a 'code smell' example?",back:"Very long functions (should be broken up), duplicate code (should use a function), unclear variable names."},
  {id:99,bi:1,front:"What is 'defensive copying'?",back:"Making a copy of data before passing it to a function, so the function can't accidentally change the original."},
  {id:100,bi:1,front:"What is 'separation of concerns'?",back:"Organizing code so each part handles one specific responsibility, making code easier to maintain and test."},

  // ============================================================
  // BIG IDEA 2: DATA (DAT) — 100 cards
  // ============================================================
  {id:101,bi:2,front:"What is a Bit?",back:"The smallest unit of data in computing, representing either a 0 or 1 (binary digit). Everything in a computer is stored as bits."},
  {id:102,bi:2,front:"What is Binary Number System?",back:"Base-2 number system using only 0s and 1s. Each position represents a power of 2. Used because digital circuits have two states: on/off."},
  {id:103,bi:2,front:"How many values can n bits represent?",back:"2^n values. 1 bit = 2 values, 8 bits = 256 values, 16 bits = 65,536 values, 32 bits = ~4.3 billion values."},
  {id:104,bi:2,front:"What is Lossless Compression?",back:"Compression allowing exact original data reconstruction. No data is lost. Examples: ZIP, PNG, FLAC."},
  {id:105,bi:2,front:"What is Lossy Compression?",back:"Compression removing some data to reduce size — original cannot be perfectly reconstructed. Examples: JPEG, MP3."},
  {id:106,bi:2,front:"What is Metadata?",back:"Data about other data. Photo metadata includes: date taken, GPS location, camera model. Not the content itself."},
  {id:107,bi:2,front:"What is a Byte?",back:"8 bits. Represents 256 different values (0–255). KB ≈ 1,000 bytes, MB ≈ 1,000,000 bytes, GB ≈ 1 billion bytes."},
  {id:108,bi:2,front:"Convert binary 1010 to decimal.",back:"1×2³ + 0×2² + 1×2¹ + 0×2⁰ = 8 + 0 + 2 + 0 = 10"},
  {id:109,bi:2,front:"Convert binary 1101 to decimal.",back:"1×8 + 1×4 + 0×2 + 1×1 = 8 + 4 + 0 + 1 = 13"},
  {id:110,bi:2,front:"Convert binary 11111111 to decimal.",back:"128+64+32+16+8+4+2+1 = 255 (maximum value of 1 byte)"},
  {id:111,bi:2,front:"What is an Overflow Error?",back:"When a value is too large to store in available bits, causing incorrect results or wrapping around."},
  {id:112,bi:2,front:"What is Run-Length Encoding?",back:"Lossless compression replacing repeated sequences with a count: 'AAAAABBB' → '5A3B'."},
  {id:113,bi:2,front:"What is Huffman Coding?",back:"Lossless compression where common characters get shorter bit codes and rare characters get longer codes."},
  {id:114,bi:2,front:"What does RGB stand for?",back:"Red, Green, Blue — three color channels each 0–255 (1 byte) used to represent colors digitally."},
  {id:115,bi:2,front:"What is analog data?",back:"Continuous data with infinite possible values (temperature, sound waves, light intensity)."},
  {id:116,bi:2,front:"What is digital data?",back:"Discrete data with finite possible values, represented as bits. Converted from analog via sampling."},
  {id:117,bi:2,front:"What is sampling in digital audio?",back:"Measuring the analog sound wave at regular intervals to convert it to digital data. Higher sample rate = better quality."},
  {id:118,bi:2,front:"What is a pixel?",back:"The smallest unit of a digital image. Each pixel has a color value (often RGB). More pixels = higher resolution."},
  {id:119,bi:2,front:"What is resolution?",back:"The number of pixels in an image (width × height). Higher resolution = more detail, larger file size."},
  {id:120,bi:2,front:"What is the difference between data and information?",back:"Data is raw facts/figures. Information is data that has been processed and has meaning in context."},
  {id:121,bi:2,front:"What is data abstraction?",back:"Managing complexity by hiding implementation details. Using a list without knowing how it's stored in memory."},
  {id:122,bi:2,front:"What is a database?",back:"An organized collection of structured data, typically stored and accessed electronically. Managed by DBMS."},
  {id:123,bi:2,front:"What is SQL?",back:"Structured Query Language — used to query and manipulate relational databases (SELECT, INSERT, UPDATE, DELETE)."},
  {id:124,bi:2,front:"What is Big Data?",back:"Datasets so large they require special tools to process. Characterized by Volume, Velocity, Variety (the 3 Vs)."},
  {id:125,bi:2,front:"What is data cleaning?",back:"Removing duplicates, fixing errors, filling missing values in raw data before analysis — essential for accurate results."},
  {id:126,bi:2,front:"What is data visualization?",back:"Representing data graphically (charts, graphs, maps) to reveal patterns not obvious in raw numbers."},
  {id:127,bi:2,front:"What is a scatter plot?",back:"A chart plotting individual data points on two axes — reveals correlations and distribution patterns."},
  {id:128,bi:2,front:"What is correlation?",back:"A statistical relationship between two variables — when one changes, the other tends to change too."},
  {id:129,bi:2,front:"What is the difference between correlation and causation?",back:"Correlation means two things tend to change together. Causation means one thing directly causes another. Correlation ≠ causation."},
  {id:130,bi:2,front:"What is an outlier in data?",back:"A data point significantly different from others — may indicate errors, rare events, or important discoveries."},
  {id:131,bi:2,front:"What is the mean?",back:"The arithmetic average: sum of all values divided by the count of values."},
  {id:132,bi:2,front:"What is the median?",back:"The middle value when data is sorted. Less affected by outliers than the mean."},
  {id:133,bi:2,front:"What is the mode?",back:"The value that appears most frequently in a dataset."},
  {id:134,bi:2,front:"What is data filtering?",back:"Showing only data that meets certain criteria, reducing a dataset to relevant records."},
  {id:135,bi:2,front:"What is data aggregation?",back:"Combining multiple pieces of data into a summary (sum, average, count). Also: combining datasets to reveal more info."},
  {id:136,bi:2,front:"What is the 'data privacy' concern with aggregation?",back:"Combining individually harmless data points can reveal sensitive information — location + purchase data reveals health conditions."},
  {id:137,bi:2,front:"What is PII?",back:"Personally Identifiable Information — data identifying an individual: name, SSN, address, phone, email, biometrics."},
  {id:138,bi:2,front:"What is data encryption?",back:"Converting plaintext into unreadable ciphertext using an algorithm and key, so only authorized parties can read it."},
  {id:139,bi:2,front:"What is symmetric encryption?",back:"The same key is used for both encryption and decryption. Fast, but key must be shared securely."},
  {id:140,bi:2,front:"What is asymmetric encryption?",back:"Public key encrypts, private key decrypts. Anyone can encrypt a message to you; only you can decrypt it."},
  {id:141,bi:2,front:"What is a Caesar cipher?",back:"A simple substitution cipher shifting each letter by a fixed number. Example: A→D, B→E with shift of 3."},
  {id:142,bi:2,front:"What is the Vigenère cipher?",back:"An encryption using a keyword where each letter of the key determines a different shift — stronger than Caesar."},
  {id:143,bi:2,front:"What is a hash function?",back:"A one-way function converting input to a fixed-size output (hash). Same input always gives same hash. Cannot be reversed."},
  {id:144,bi:2,front:"What are hashes used for?",back:"Storing passwords securely, verifying file integrity, digital signatures. Not encryption — cannot be reversed."},
  {id:145,bi:2,front:"What is TLS/SSL?",back:"Protocols providing encrypted, authenticated connections over the internet. Used by HTTPS to secure web browsing."},
  {id:146,bi:2,front:"What does the padlock in a browser mean?",back:"The connection uses HTTPS/TLS encryption — data between browser and server is protected from eavesdropping."},
  {id:147,bi:2,front:"What is a digital certificate?",back:"Issued by Certificate Authorities, verifies a website is who it claims to be, preventing man-in-the-middle attacks."},
  {id:148,bi:2,front:"What is a Certificate Authority (CA)?",back:"A trusted organization that verifies website identities and issues digital certificates for HTTPS."},
  {id:149,bi:2,front:"What is data compression ratio?",back:"Original size ÷ compressed size. A ratio of 10:1 means the compressed file is 10 times smaller."},
  {id:150,bi:2,front:"Why is lossless compression preferred for text?",back:"Text requires exact reproduction — even one wrong character changes meaning. Lossy compression is unacceptable."},
  {id:151,bi:2,front:"What is hexadecimal?",back:"Base-16 number system using digits 0–9 and letters A–F. Used in computing because it compactly represents 4 bits."},
  {id:152,bi:2,front:"What is 0xFF in decimal?",back:"F=15, so 0xFF = 15×16 + 15×1 = 240 + 15 = 255."},
  {id:153,bi:2,front:"What is data redundancy?",back:"Storing the same data in multiple places. Wastes space but increases reliability and availability."},
  {id:154,bi:2,front:"What is cloud storage?",back:"Storing data on remote servers accessible over the internet rather than on local devices."},
  {id:155,bi:2,front:"What is a CSV file?",back:"Comma-Separated Values — a plain text file storing tabular data with commas separating values in each row."},
  {id:156,bi:2,front:"What is JSON?",back:"JavaScript Object Notation — a lightweight data format using key-value pairs, widely used for APIs and config files."},
  {id:157,bi:2,front:"What is XML?",back:"Extensible Markup Language — a data format using tags to structure data, similar to HTML but for data not display."},
  {id:158,bi:2,front:"What is a data type?",back:"The category of data: integer, float, string, boolean, list. Determines what operations can be performed."},
  {id:159,bi:2,front:"What is floating point?",back:"A way to represent decimal numbers in binary. Limited precision can cause rounding errors in computation."},
  {id:160,bi:2,front:"What is a rounding error?",back:"Imprecision from representing decimal fractions in binary — e.g., 0.1 + 0.2 ≠ exactly 0.3 in most computers."},
  {id:161,bi:2,front:"What is data normalization?",back:"Organizing data in a database to reduce redundancy and improve data integrity."},
  {id:162,bi:2,front:"What is a primary key in a database?",back:"A unique identifier for each record in a table (e.g., student ID). No two records can have the same primary key."},
  {id:163,bi:2,front:"What is a foreign key?",back:"A field in one table referencing the primary key of another table, creating a relationship between tables."},
  {id:164,bi:2,front:"What is data mining?",back:"Using algorithms to find patterns, correlations, and insights in large datasets."},
  {id:165,bi:2,front:"What is machine learning?",back:"A type of AI where algorithms learn patterns from data rather than following explicitly programmed rules."},
  {id:166,bi:2,front:"What is training data in ML?",back:"The dataset used to teach a machine learning model — it learns patterns from these examples."},
  {id:167,bi:2,front:"What is overfitting in ML?",back:"When a model memorizes training data too well and performs poorly on new, unseen data."},
  {id:168,bi:2,front:"What is a data breach?",back:"Unauthorized access to confidential data — when private data is exposed to people who shouldn't have it."},
  {id:169,bi:2,front:"What is data integrity?",back:"Ensuring data is accurate, consistent, and unaltered from its original state."},
  {id:170,bi:2,front:"What is steganography?",back:"Hiding secret data inside ordinary files (images, audio) without detection — the hidden data is invisible."},
  {id:171,bi:2,front:"What is a checksum?",back:"A value computed from data used to detect errors — if the file changes, the checksum changes too."},
  {id:172,bi:2,front:"What is base 10 (decimal)?",back:"The number system humans use with 10 digits (0–9). Each position is a power of 10."},
  {id:173,bi:2,front:"Convert decimal 25 to binary.",back:"25 = 16+8+1 = 11001 in binary."},
  {id:174,bi:2,front:"Convert decimal 42 to binary.",back:"42 = 32+8+2 = 101010 in binary."},
  {id:175,bi:2,front:"What is color depth?",back:"The number of bits used to represent the color of one pixel. 8-bit = 256 colors, 24-bit = 16 million colors."},
  {id:176,bi:2,front:"What is lossless audio format?",back:"FLAC, WAV, AIFF — the exact original audio is preserved after compression/storage."},
  {id:177,bi:2,front:"What is lossy audio format?",back:"MP3, AAC, OGG — some audio frequencies are removed to reduce file size. Some quality is permanently lost."},
  {id:178,bi:2,front:"What is data throughput?",back:"The amount of data transferred over a network in a given time — measured in bits per second (Mbps, Gbps)."},
  {id:179,bi:2,front:"What is bandwidth?",back:"The maximum capacity of a network connection — the theoretical maximum data transfer rate."},
  {id:180,bi:2,front:"What is latency?",back:"The delay between sending data and receiving it — measured in milliseconds. Different from bandwidth."},
  {id:181,bi:2,front:"What is data deduplication?",back:"A storage optimization removing duplicate copies of data, keeping only one copy to save space."},
  {id:182,bi:2,front:"What is a data warehouse?",back:"A large storage system designed for querying and analyzing historical data from multiple sources."},
  {id:183,bi:2,front:"What is the difference between structured and unstructured data?",back:"Structured: organized in rows/columns (databases, spreadsheets). Unstructured: emails, images, videos, social posts."},
  {id:184,bi:2,front:"What is a data model?",back:"An abstract representation of how data is organized and related in a database or system."},
  {id:185,bi:2,front:"What is two's complement?",back:"The standard method for representing negative integers in binary. Flip all bits, then add 1."},
  {id:186,bi:2,front:"What is ASCII?",back:"American Standard Code for Information Interchange — assigns numbers to characters. 'A'=65, 'a'=97, '0'=48."},
  {id:187,bi:2,front:"What is Unicode?",back:"A universal character encoding covering virtually all world languages and symbols. UTF-8 is the most common encoding."},
  {id:188,bi:2,front:"What is data serialization?",back:"Converting data structures to a format that can be stored or transmitted, then reconstructed later (JSON, XML, CSV)."},
  {id:189,bi:2,front:"What are the '3 Vs' of Big Data?",back:"Volume (huge amount of data), Velocity (data arrives rapidly), Variety (many different types and formats)."},
  {id:190,bi:2,front:"What is a 'data lake'?",back:"A storage repository holding raw data in native format until needed — more flexible than a structured data warehouse."},
  {id:191,bi:2,front:"What is differential privacy?",back:"A technique allowing analysis of datasets while mathematically guaranteeing individual records cannot be identified."},
  {id:192,bi:2,front:"What is k-anonymity?",back:"A privacy property ensuring each record is indistinguishable from at least k-1 other records for key attributes."},
  {id:193,bi:2,front:"What is data provenance?",back:"Tracking the origin and history of data — where it came from, how it was processed, ensuring trustworthiness."},
  {id:194,bi:2,front:"What is a confusion matrix?",back:"A table showing ML model performance: true positives, false positives, true negatives, false negatives."},
  {id:195,bi:2,front:"What is precision in ML?",back:"Of all items the model labeled positive, what fraction were actually positive? TP / (TP + FP)."},
  {id:196,bi:2,front:"What is recall in ML?",back:"Of all actual positives, what fraction did the model correctly identify? TP / (TP + FN)."},
  {id:197,bi:2,front:"What is a false positive?",back:"The model predicted positive but the answer is actually negative. Also called a 'Type I error'."},
  {id:198,bi:2,front:"What is a false negative?",back:"The model predicted negative but the answer is actually positive. Also called a 'Type II error'."},
  {id:199,bi:2,front:"What is the significance of the number 256 in computing?",back:"2^8 = 256. It's the number of values a single byte can represent (0–255). Appears constantly in computing."},
  {id:200,bi:2,front:"What is signal-to-noise ratio in data?",back:"The proportion of meaningful signal vs. irrelevant noise in a dataset. High noise makes analysis harder."},

  // ============================================================
  // BIG IDEA 3: ALGORITHMS & PROGRAMMING (AAP) — 100 cards
  // ============================================================
  {id:201,bi:3,front:"What is a Variable?",back:"A named storage location holding a value that can change as the program runs. Assigned with ← in AP pseudocode."},
  {id:202,bi:3,front:"What is a Conditional Statement?",back:"An IF/ELSE statement making decisions based on whether a condition is true or false."},
  {id:203,bi:3,front:"What is an Algorithm?",back:"A finite set of step-by-step instructions for solving a problem. Must be precise, unambiguous, and terminate."},
  {id:204,bi:3,front:"What is Iteration?",back:"Repeating a block of code using loops (REPEAT n TIMES, REPEAT UNTIL condition, FOR EACH item IN list)."},
  {id:205,bi:3,front:"What is a Procedure (Function)?",back:"A named group of instructions called by name. Takes parameters as input, may return a value. Enables code reuse."},
  {id:206,bi:3,front:"What is a List?",back:"An ordered collection of items accessed by index. In AP pseudocode, lists are 1-indexed. Supports INSERT, APPEND, REMOVE."},
  {id:207,bi:3,front:"What is a Boolean Expression?",back:"An expression evaluating to true or false. Uses comparison operators (=, ≠, <, >) and logical operators (AND, OR, NOT)."},
  {id:208,bi:3,front:"What is Linear Search?",back:"Checking each element one by one until target is found or list ends. Works on unsorted lists. O(n) time."},
  {id:209,bi:3,front:"What is Binary Search?",back:"Efficiently searches sorted lists by repeatedly halving the search range. O(log n). Requires sorted data."},
  {id:210,bi:3,front:"What is an Undecidable Problem?",back:"A problem for which no algorithm can correctly answer yes or no for all possible inputs. The Halting Problem is the example."},
  {id:211,bi:3,front:"What is the Halting Problem?",back:"Determining whether an arbitrary program will halt or run forever. Proved undecidable by Turing — no algorithm can always solve it."},
  {id:212,bi:3,front:"What is Abstraction in Programming?",back:"Simplifying complexity by hiding unnecessary details. Procedures hide implementation, lists manage multiple values, APIs access services."},
  {id:213,bi:3,front:"What is the MOD operator?",back:"Returns the remainder after division. 7 MOD 3 = 1. Used to check even/odd: n MOD 2 = 0 means n is even."},
  {id:214,bi:3,front:"What is a parameter?",back:"A variable in a procedure definition that receives a value when the procedure is called."},
  {id:215,bi:3,front:"What is an argument?",back:"The actual value passed to a procedure when calling it. Arguments fill in parameters."},
  {id:216,bi:3,front:"What does RETURN do?",back:"Immediately exits a procedure and sends a value back to the caller. Not all procedures return a value."},
  {id:217,bi:3,front:"What is recursion?",back:"When a procedure calls itself. Must have a base case to stop, otherwise it causes infinite recursion."},
  {id:218,bi:3,front:"What is a base case in recursion?",back:"The condition that stops recursive calls. Without a base case, recursion never terminates (stack overflow)."},
  {id:219,bi:3,front:"What is the call stack?",back:"Memory structure tracking active function calls. Each call adds a frame; RETURN removes it."},
  {id:220,bi:3,front:"What is O(n) time complexity?",back:"Linear time — runtime grows proportionally with input size. Doubling input doubles runtime. Example: linear search."},
  {id:221,bi:3,front:"What is O(log n) time complexity?",back:"Logarithmic time — runtime grows very slowly. Doubling input adds just one step. Example: binary search."},
  {id:222,bi:3,front:"What is O(n²) time complexity?",back:"Quadratic time — runtime grows with the square of input size. Doubling input quadruples runtime. Example: bubble sort."},
  {id:223,bi:3,front:"What is O(1) time complexity?",back:"Constant time — runtime doesn't change regardless of input size. Example: accessing an array by index."},
  {id:224,bi:3,front:"What is bubble sort?",back:"A sorting algorithm repeatedly swapping adjacent elements that are out of order. O(n²) — simple but inefficient."},
  {id:225,bi:3,front:"What is selection sort?",back:"Finds the minimum element and moves it to the front repeatedly. O(n²) time."},
  {id:226,bi:3,front:"What is insertion sort?",back:"Builds sorted list one element at a time by inserting each into the correct position. O(n²) worst case."},
  {id:227,bi:3,front:"What is merge sort?",back:"Divide-and-conquer sorting: split list in half, sort each half recursively, merge. O(n log n) — much more efficient."},
  {id:228,bi:3,front:"What is quicksort?",back:"Picks a pivot, partitions around it, recursively sorts partitions. Average O(n log n), worst case O(n²)."},
  {id:229,bi:3,front:"What is a stack data structure?",back:"Last In, First Out (LIFO). Like a stack of plates — you can only push to or pop from the top."},
  {id:230,bi:3,front:"What is a queue data structure?",back:"First In, First Out (FIFO). Like a line — items are added to the back and removed from the front."},
  {id:231,bi:3,front:"What is a dictionary (hash map)?",back:"A data structure storing key-value pairs. Fast O(1) lookup by key. Example: {'name': 'Alice', 'age': 17}."},
  {id:232,bi:3,front:"What is a tree data structure?",back:"Hierarchical structure with a root node and child nodes. Binary trees have at most 2 children per node."},
  {id:233,bi:3,front:"What is a graph data structure?",back:"Nodes (vertices) connected by edges. Can model networks, maps, relationships. May have weighted edges."},
  {id:234,bi:3,front:"What is the AP pseudocode assignment operator?",back:"The left arrow ← : x ← 5 assigns 5 to x. NOT the equals sign."},
  {id:235,bi:3,front:"What is APPEND in AP pseudocode?",back:"APPEND(list, value) — adds a value to the end of a list."},
  {id:236,bi:3,front:"What is INSERT in AP pseudocode?",back:"INSERT(list, index, value) — inserts a value at a specific index, shifting other elements right."},
  {id:237,bi:3,front:"What is REMOVE in AP pseudocode?",back:"REMOVE(list, index) — removes the element at a specific index, shifting other elements left."},
  {id:238,bi:3,front:"What is LENGTH in AP pseudocode?",back:"LENGTH(list) — returns the number of elements in the list."},
  {id:239,bi:3,front:"What does FOR EACH do in AP pseudocode?",back:"FOR EACH item IN list { } — iterates through every element in the list, one at a time."},
  {id:240,bi:3,front:"What is REPEAT TIMES vs REPEAT UNTIL?",back:"REPEAT n TIMES loops exactly n times. REPEAT UNTIL condition loops until condition becomes true."},
  {id:241,bi:3,front:"What is string concatenation?",back:"Combining two strings together: 'Hello' + ' ' + 'World' = 'Hello World'."},
  {id:242,bi:3,front:"What is the result of TRUE AND FALSE?",back:"FALSE. AND requires BOTH to be true."},
  {id:243,bi:3,front:"What is the result of TRUE OR FALSE?",back:"TRUE. OR requires AT LEAST ONE to be true."},
  {id:244,bi:3,front:"What is the result of NOT TRUE?",back:"FALSE. NOT flips the boolean value."},
  {id:245,bi:3,front:"What is De Morgan's Law?",back:"NOT(A AND B) = (NOT A) OR (NOT B). NOT(A OR B) = (NOT A) AND (NOT B). Useful for simplifying boolean expressions."},
  {id:246,bi:3,front:"Trace: x←3, y←x*2+1, DISPLAY y",back:"x=3, y=3*2+1=7, displays 7."},
  {id:247,bi:3,front:"What is a nested loop?",back:"A loop inside another loop. The inner loop runs completely for each iteration of the outer loop. Common in 2D array processing."},
  {id:248,bi:3,front:"What is a nested conditional?",back:"An IF statement inside another IF statement. Inner condition only evaluated if outer condition is true."},
  {id:249,bi:3,front:"What is short-circuit evaluation?",back:"In AND expressions, if the first operand is false, the second isn't evaluated. In OR, if first is true, second isn't."},
  {id:250,bi:3,front:"What is a heuristic algorithm?",back:"An algorithm that finds a good (but not necessarily optimal) solution quickly when finding the perfect solution is too slow."},
  {id:251,bi:3,front:"What is a greedy algorithm?",back:"Makes the locally optimal choice at each step hoping it leads to a globally optimal solution. Fast but not always optimal."},
  {id:252,bi:3,front:"What is dynamic programming?",back:"Solving complex problems by breaking into overlapping subproblems and storing results to avoid recomputation."},
  {id:253,bi:3,front:"What is memoization?",back:"Caching function results so they don't need to be recomputed when called with the same arguments again."},
  {id:254,bi:3,front:"What is the Traveling Salesman Problem?",back:"Finding the shortest route visiting all cities exactly once. NP-hard — no known polynomial-time solution. Uses heuristics."},
  {id:255,bi:3,front:"What is an NP problem?",back:"A problem where solutions can be verified quickly but no efficient algorithm for finding solutions is known."},
  {id:256,bi:3,front:"What is a decidable problem?",back:"A problem for which an algorithm always produces a correct yes/no answer in finite time."},
  {id:257,bi:3,front:"What is an approximation algorithm?",back:"An algorithm finding a solution within a guaranteed factor of optimal when exact solution is too slow."},
  {id:258,bi:3,front:"What is the efficiency of binary search on 1 million items?",back:"At most log₂(1,000,000) ≈ 20 comparisons. Linear search could take up to 1,000,000 comparisons."},
  {id:259,bi:3,front:"What is a sentinel value?",back:"A special value marking the end of a list or signaling a special condition (e.g., -1 to mean 'not found')."},
  {id:260,bi:3,front:"What is array indexing in AP pseudocode?",back:"AP lists are 1-indexed: myList[1] is the first element. Common trap — most languages use 0-indexed arrays."},
  {id:261,bi:3,front:"Trace: list←[3,1,4,1,5], DISPLAY list[3]",back:"Displays 4 (AP lists are 1-indexed, so index 3 is the third element)."},
  {id:262,bi:3,front:"What is a 2D list (matrix)?",back:"A list of lists. Accessed with two indices: matrix[row][col]. Used for grids, tables, images."},
  {id:263,bi:3,front:"What is a string in programming?",back:"A sequence of characters. In AP pseudocode, strings are enclosed in quotes: 'Hello World'."},
  {id:264,bi:3,front:"What is string length?",back:"The number of characters in a string. 'Hello' has length 5."},
  {id:265,bi:3,front:"What is substring?",back:"A portion of a string. 'Hello World' substring starting at 1 with length 5 is 'Hello'."},
  {id:266,bi:3,front:"What is type conversion?",back:"Changing a value from one data type to another. String '42' → integer 42. Integer 5 → string '5'."},
  {id:267,bi:3,front:"What is integer division?",back:"Division that discards the fractional part. 7 ÷ 2 = 3 (not 3.5) in integer division."},
  {id:268,bi:3,front:"What is a swap in sorting?",back:"Exchanging the positions of two elements in a list. Often uses a temporary variable: temp←a, a←b, b←temp."},
  {id:269,bi:3,front:"What does DISPLAY do in AP pseudocode?",back:"Outputs a value to the screen/console. DISPLAY(x) shows the value of x."},
  {id:270,bi:3,front:"What does INPUT do in AP pseudocode?",back:"Gets a value from the user. x ← INPUT() stores user input in variable x."},
  {id:271,bi:3,front:"What is the purpose of a return value?",back:"Allows a procedure to pass a computed result back to the code that called it, enabling composition of procedures."},
  {id:272,bi:3,front:"What is function composition?",back:"Using the output of one function as the input to another: result ← outer(inner(x))."},
  {id:273,bi:3,front:"What is a side effect in programming?",back:"When a function modifies state outside itself (changes a global variable, writes to a file) beyond returning a value."},
  {id:274,bi:3,front:"What is a pure function?",back:"A function with no side effects that always returns the same output for the same input — easier to test and reason about."},
  {id:275,bi:3,front:"What is an accumulator pattern?",back:"Starting with an initial value (0 or []) and adding to it in a loop. Common for summing or collecting items."},
  {id:276,bi:3,front:"What is a counter variable?",back:"A variable incremented each loop iteration to count occurrences or track position."},
  {id:277,bi:3,front:"What is a minimum/maximum finding algorithm?",back:"Initialize min/max to first element, compare each subsequent element, update if smaller/larger. O(n) time."},
  {id:278,bi:3,front:"What is a search algorithm's 'worst case'?",back:"The maximum steps needed for any input. Linear search worst case = n (not found). Binary search = log n."},
  {id:279,bi:3,front:"What is a search algorithm's 'best case'?",back:"Minimum steps for the easiest input. Linear search best case = 1 (found at first position)."},
  {id:280,bi:3,front:"What is 'average case' complexity?",back:"The expected runtime for a random input. Often more realistic than worst case for practical analysis."},
  {id:281,bi:3,front:"What is tail recursion?",back:"Recursion where the recursive call is the very last operation. Can be optimized to avoid stack overflow."},
  {id:282,bi:3,front:"What is a linked list?",back:"A data structure where each element (node) stores its value and a pointer to the next node. O(n) access by index."},
  {id:283,bi:3,front:"What is the difference between a list and an array?",back:"Arrays have fixed size, same type. Lists (in AP pseudocode) can grow/shrink and hold mixed types."},
  {id:284,bi:3,front:"What is Big O notation used for?",back:"Describing how an algorithm's runtime or space requirements scale with input size, ignoring constants."},
  {id:285,bi:3,front:"What is space complexity?",back:"How much memory an algorithm uses relative to input size. Separate from time complexity."},
  {id:286,bi:3,front:"What is a boolean?",back:"A data type with only two values: true or false. Named after mathematician George Boole."},
  {id:287,bi:3,front:"What is a ternary operator?",back:"A shorthand conditional: condition ? valueIfTrue : valueIFalse. Returns one of two values based on condition."},
  {id:288,bi:3,front:"What is 'early termination' in search?",back:"Stopping a loop as soon as the answer is found rather than processing the entire list — more efficient."},
  {id:289,bi:3,front:"What is a brute force algorithm?",back:"Tries all possible solutions until finding the correct one. Simple but often very slow for large inputs."},
  {id:290,bi:3,front:"What is 'algorithm correctness'?",back:"An algorithm is correct if it produces the right answer for every valid input in finite time."},
  {id:291,bi:3,front:"What is pseudocode used for?",back:"Planning algorithms before coding. Language-independent, focuses on logic not syntax."},
  {id:292,bi:3,front:"What is a 'trace table'?",back:"A table showing variable values at each step of algorithm execution — used to verify algorithm correctness."},
  {id:293,bi:3,front:"What is the difference between = and ← in AP pseudocode?",back:"← is the assignment operator (x ← 5 sets x to 5). = is the comparison operator (x = 5 tests if x equals 5)."},
  {id:294,bi:3,front:"What are the three components of an algorithm?",back:"Sequencing (steps in order), Selection (decisions/conditionals), Iteration (repetition/loops)."},
  {id:295,bi:3,front:"What is a graph traversal algorithm?",back:"An algorithm visiting every node in a graph. BFS (Breadth-First Search) explores level by level; DFS explores depth-first."},
  {id:296,bi:3,front:"What is Dijkstra's algorithm?",back:"Finds shortest paths from a source node to all other nodes in a weighted graph. Used in GPS navigation."},
  {id:297,bi:3,front:"What is the difference between an algorithm and a program?",back:"An algorithm is an abstract step-by-step solution. A program is the concrete implementation of an algorithm in a specific language."},
  {id:298,bi:3,front:"What is a flowchart symbol for a decision?",back:"A diamond shape. Contains a yes/no question; two arrows leave — one for yes, one for no."},
  {id:299,bi:3,front:"What are the limits of algorithms?",back:"Some problems are undecidable (Halting Problem). Some are decidable but require too much time (NP-hard). Heuristics help."},
  {id:300,bi:3,front:"What is string comparison?",back:"Comparing strings alphabetically/lexicographically. 'apple' < 'banana' because 'a' comes before 'b'."},

  // ============================================================
  // BIG IDEA 4: COMPUTER SYSTEMS & NETWORKS (CSN) — 100 cards
  // ============================================================
  {id:301,bi:4,front:"What is the Internet?",back:"A global 'network of networks' — interconnected computers communicating using agreed-upon protocols. Built on existing infrastructure."},
  {id:302,bi:4,front:"What is an IP Address?",back:"A numerical label assigned to each device on a network. IPv4: 32-bit (192.168.1.1). IPv6: 128-bit for more devices."},
  {id:303,bi:4,front:"What is a Protocol?",back:"Agreed-upon rules defining how data is transmitted over a network. Examples: TCP/IP, HTTP, HTTPS, DNS."},
  {id:304,bi:4,front:"What is TCP/IP?",back:"The foundational internet protocol suite. IP handles addressing/routing; TCP ensures reliable, ordered delivery."},
  {id:305,bi:4,front:"What is DNS?",back:"Domain Name System — translates human-readable domain names (google.com) to IP addresses. The internet's phonebook."},
  {id:306,bi:4,front:"What is Packet Switching?",back:"Data is broken into packets that travel independently and are reassembled at the destination. Enables fault tolerance."},
  {id:307,bi:4,front:"What is Encryption?",back:"Converting readable data (plaintext) into unreadable format (ciphertext) using a key, so only authorized parties can read it."},
  {id:308,bi:4,front:"What is a DDoS Attack?",back:"Distributed Denial of Service — overwhelming a server with traffic from many sources, making it unavailable to legitimate users."},
  {id:309,bi:4,front:"What is Fault Tolerance?",back:"A system continuing to operate when components fail. The internet reroutes data around failed nodes."},
  {id:310,bi:4,front:"What is Parallel Computing?",back:"Breaking a task into subtasks running simultaneously on multiple processors/cores to speed up computation."},
  {id:311,bi:4,front:"What is IPv4?",back:"Internet Protocol version 4. Uses 32-bit addresses (4 groups of 0-255 like 192.168.0.1). ~4.3 billion addresses — nearly exhausted."},
  {id:312,bi:4,front:"What is IPv6?",back:"Internet Protocol version 6. Uses 128-bit addresses. Virtually unlimited — created to replace IPv4 due to address exhaustion."},
  {id:313,bi:4,front:"What is HTTP?",back:"HyperText Transfer Protocol — the foundation of data communication on the web. Unencrypted."},
  {id:314,bi:4,front:"What is HTTPS?",back:"HTTP Secure — HTTP with TLS encryption. Your data is protected from eavesdropping. Identified by padlock icon."},
  {id:315,bi:4,front:"What is a router?",back:"A network device forwarding data packets between networks, directing traffic along the best available path."},
  {id:316,bi:4,front:"What is a switch?",back:"A network device connecting devices within a local network (LAN), directing traffic only to the intended device."},
  {id:317,bi:4,front:"What is a LAN?",back:"Local Area Network — a network covering a small area (home, office). Usually connected via Ethernet or Wi-Fi."},
  {id:318,bi:4,front:"What is a WAN?",back:"Wide Area Network — a network covering large geographic areas. The internet is the largest WAN."},
  {id:319,bi:4,front:"What is Wi-Fi?",back:"Wireless network technology using radio waves to connect devices. Based on IEEE 802.11 standards."},
  {id:320,bi:4,front:"What is Ethernet?",back:"Wired network technology connecting devices with cables. Faster and more reliable than Wi-Fi."},
  {id:321,bi:4,front:"What is a firewall?",back:"Security software/hardware filtering network traffic based on rules — blocks unauthorized access."},
  {id:322,bi:4,front:"What is a VPN?",back:"Virtual Private Network — encrypts all traffic between a device and a server, hiding activity from ISPs and others."},
  {id:323,bi:4,front:"What is a botnet?",back:"A network of computers infected with malware, controlled remotely by attackers. Used for DDoS attacks and spam."},
  {id:324,bi:4,front:"What is malware?",back:"Malicious software designed to damage or gain unauthorized access. Includes viruses, worms, trojans, ransomware."},
  {id:325,bi:4,front:"What is a virus?",back:"Malware that attaches to legitimate programs and spreads by self-replicating when the host program runs."},
  {id:326,bi:4,front:"What is a worm?",back:"Self-replicating malware spreading through networks without attaching to a host program."},
  {id:327,bi:4,front:"What is ransomware?",back:"Malware encrypting victim's files and demanding payment for the decryption key."},
  {id:328,bi:4,front:"What is spyware?",back:"Malware secretly monitoring user activity and sending data to attackers without the user's knowledge."},
  {id:329,bi:4,front:"What is a trojan horse?",back:"Malware disguised as legitimate software. Unlike viruses, it doesn't self-replicate but creates backdoors."},
  {id:330,bi:4,front:"What is phishing?",back:"Fraudulent emails/websites tricking users into revealing credentials by impersonating trustworthy entities."},
  {id:331,bi:4,front:"What is social engineering?",back:"Manipulating humans through deception to gain unauthorized access — exploits human psychology, not technical flaws."},
  {id:332,bi:4,front:"What is multi-factor authentication (MFA)?",back:"Requiring two or more verification methods: something you know (password) + something you have (phone) + something you are (fingerprint)."},
  {id:333,bi:4,front:"What is a man-in-the-middle attack?",back:"An attacker secretly intercepts and possibly alters communications between two parties who believe they're communicating directly."},
  {id:334,bi:4,front:"What is SQL injection?",back:"Inserting malicious SQL code into input fields to manipulate a database — one of the most common web attacks."},
  {id:335,bi:4,front:"What is cross-site scripting (XSS)?",back:"Injecting malicious scripts into web pages viewed by other users, stealing cookies or redirecting to malicious sites."},
  {id:336,bi:4,front:"What is a zero-day vulnerability?",back:"A security flaw unknown to the software vendor, giving attackers time to exploit it before a patch is released."},
  {id:337,bi:4,front:"What is a patch?",back:"A software update fixing known security vulnerabilities or bugs. Installing patches is crucial for security."},
  {id:338,bi:4,front:"What is public-key cryptography?",back:"Asymmetric encryption using a key pair: public key (shared freely) encrypts; private key (secret) decrypts."},
  {id:339,bi:4,front:"What is a digital signature?",back:"Using a private key to sign data — others verify with the public key, confirming the signer's identity."},
  {id:340,bi:4,front:"What is certificate pinning?",back:"Hardcoding a server's expected certificate in an app, preventing man-in-the-middle attacks with fake certificates."},
  {id:341,bi:4,front:"What is UDP?",back:"User Datagram Protocol — faster than TCP but unreliable (no guarantee packets arrive). Used for gaming, video streaming."},
  {id:342,bi:4,front:"What is a packet?",back:"A small chunk of data transmitted across a network. Contains header (source, destination, sequence number) and payload (actual data)."},
  {id:343,bi:4,front:"What is packet header?",back:"Metadata at the beginning of a packet containing source IP, destination IP, sequence number, and protocol information."},
  {id:344,bi:4,front:"What is packet reassembly?",back:"The process of combining received packets (which may arrive out of order) back into the original complete message."},
  {id:345,bi:4,front:"What is network latency?",back:"Time delay for data to travel from source to destination. Affected by distance, congestion, and routing."},
  {id:346,bi:4,front:"What is the OSI model?",back:"A conceptual framework dividing network communication into 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application."},
  {id:347,bi:4,front:"What is the Application Layer (OSI)?",back:"The topmost layer — handles high-level protocols like HTTP, DNS, SMTP that applications use directly."},
  {id:348,bi:4,front:"What is the Transport Layer (OSI)?",back:"Handles end-to-end communication, reliability, and flow control. TCP and UDP operate at this layer."},
  {id:349,bi:4,front:"What is the Network Layer (OSI)?",back:"Handles logical addressing and routing of data packets. IP operates at this layer."},
  {id:350,bi:4,front:"What is the difference between the internet and the web?",back:"Internet: global infrastructure of connected computers. Web: a service using HTTP to access websites. Email, gaming also use the internet."},
  {id:351,bi:4,front:"What is a URL?",back:"Uniform Resource Locator — the address of a web resource: protocol://domain/path (https://google.com/search)."},
  {id:352,bi:4,front:"What is a domain name?",back:"Human-readable web address (google.com). DNS translates it to an IP address for routing."},
  {id:353,bi:4,front:"What is a TLD?",back:"Top-Level Domain — the suffix of a domain (.com, .org, .edu, .gov). Indicates type or country."},
  {id:354,bi:4,front:"What is a web server?",back:"Computer software serving web pages in response to HTTP requests from browsers."},
  {id:355,bi:4,front:"What is a web browser?",back:"Software retrieving and displaying web pages (HTTP client). Examples: Chrome, Firefox, Safari."},
  {id:356,bi:4,front:"What is the client-server model?",back:"Clients request resources; servers provide them. The web, email, and most internet services use this model."},
  {id:357,bi:4,front:"What is peer-to-peer (P2P) networking?",back:"Each node can act as both client and server. No central authority. Used in BitTorrent, blockchain."},
  {id:358,bi:4,front:"What is cloud computing?",back:"Delivering computing services (servers, storage, databases, software) over the internet on demand."},
  {id:359,bi:4,front:"What is distributed computing?",back:"Using multiple networked computers to solve one problem. Enables solving tasks too large for one machine."},
  {id:360,bi:4,front:"What is a CDN?",back:"Content Delivery Network — servers distributed globally serving content from the location closest to the user, reducing latency."},
  {id:361,bi:4,front:"What limits parallel computing speedup?",back:"Amdahl's Law: speedup is limited by the sequential portion. A program 50% parallel can at most double in speed."},
  {id:362,bi:4,front:"What is Amdahl's Law?",back:"The maximum speedup from parallelism is 1 / (S + (1-S)/N), where S is the sequential fraction and N is the number of processors."},
  {id:363,bi:4,front:"What is a thread in computing?",back:"A lightweight unit of execution within a process. Multi-threaded programs run multiple threads simultaneously."},
  {id:364,bi:4,front:"What is a race condition?",back:"A bug in concurrent code where the result depends on the order threads execute — can cause unpredictable behavior."},
  {id:365,bi:4,front:"What is SETI@home?",back:"A distributed computing project using volunteers' idle computers to analyze radio telescope data searching for extraterrestrial intelligence."},
  {id:366,bi:4,front:"What is Folding@home?",back:"A distributed computing project simulating protein folding to understand diseases, using volunteers' computers worldwide."},
  {id:367,bi:4,front:"What is IoT?",back:"Internet of Things — everyday physical devices (thermostats, cars, appliances) connected to and communicating via the internet."},
  {id:368,bi:4,front:"What is a MAC address?",back:"Media Access Control address — a unique hardware identifier for a network interface card. Not the same as IP address."},
  {id:369,bi:4,front:"What is NAT?",back:"Network Address Translation — allows multiple devices on a local network to share one public IP address."},
  {id:370,bi:4,front:"What is DHCP?",back:"Dynamic Host Configuration Protocol — automatically assigns IP addresses to devices joining a network."},
  {id:371,bi:4,front:"What is a subnet?",back:"A subdivision of a larger network. Improves security and performance by isolating traffic."},
  {id:372,bi:4,front:"What is traceroute?",back:"A network tool showing the path packets take from source to destination, listing each hop and its latency."},
  {id:373,bi:4,front:"What is ping?",back:"A network tool sending a packet to an address and measuring how long it takes to receive a reply (round-trip time)."},
  {id:374,bi:4,front:"What is a proxy server?",back:"An intermediary server between clients and other servers — can provide caching, anonymity, content filtering."},
  {id:375,bi:4,front:"What is Tor?",back:"A network routing traffic through multiple relays to anonymize internet activity, making tracking very difficult."},
  {id:376,bi:4,front:"What is the dark web?",back:"Parts of the internet not indexed by standard search engines, often accessed via Tor. Includes both legal and illegal content."},
  {id:377,bi:4,front:"What is FTP?",back:"File Transfer Protocol — used to transfer files between computers over a network. Unencrypted; SFTP/FTPS are secure versions."},
  {id:378,bi:4,front:"What is SMTP?",back:"Simple Mail Transfer Protocol — used for sending email between mail servers."},
  {id:379,bi:4,front:"What is SSH?",back:"Secure Shell — an encrypted protocol for securely accessing remote computers via command line."},
  {id:380,bi:4,front:"What is a port in networking?",back:"A number (0–65535) identifying a specific process/service on a device. HTTP=80, HTTPS=443, SSH=22, DNS=53."},
  {id:381,bi:4,front:"What is network topology?",back:"The physical or logical arrangement of devices in a network: bus, star, ring, mesh, hybrid."},
  {id:382,bi:4,front:"What is a mesh network?",back:"Every device connects to every other device. Highly fault tolerant — multiple paths to every node."},
  {id:383,bi:4,front:"What is a star topology?",back:"All devices connect to a central hub/switch. Easy to manage but single point of failure at the center."},
  {id:384,bi:4,front:"What makes the internet fault tolerant?",back:"Redundant paths — if one node or link fails, packets automatically reroute through alternative paths."},
  {id:385,bi:4,front:"What is network redundancy?",back:"Having multiple paths and components so failure of one doesn't disrupt the whole network."},
  {id:386,bi:4,front:"What is an SSL certificate error?",back:"Warning that a website's certificate is invalid or expired — could indicate a man-in-the-middle attack."},
  {id:387,bi:4,front:"What is key exchange in cryptography?",back:"The process of securely sharing encryption keys over an insecure channel. Diffie-Hellman is a common algorithm."},
  {id:388,bi:4,front:"What is end-to-end encryption?",back:"Data encrypted on sender's device, only decrypted on recipient's device. Even the service provider can't read it."},
  {id:389,bi:4,front:"What is a forward proxy vs reverse proxy?",back:"Forward proxy: sits in front of clients, hides client identity. Reverse proxy: sits in front of servers, hides server details."},
  {id:390,bi:4,front:"What is load balancing?",back:"Distributing network traffic across multiple servers to ensure no single server is overwhelmed."},
  {id:391,bi:4,front:"What is a honeypot in cybersecurity?",back:"A decoy system designed to lure attackers, detect attacks, and gather intelligence about attack methods."},
  {id:392,bi:4,front:"What is penetration testing?",back:"Authorized simulated attacks on a system to find security vulnerabilities before malicious attackers do."},
  {id:393,bi:4,front:"What is two-factor authentication?",back:"A security process requiring two verification methods. Even if password is stolen, account stays secure."},
  {id:394,bi:4,front:"What is a security audit?",back:"A systematic review of a system's security policies, configurations, and practices to identify vulnerabilities."},
  {id:395,bi:4,front:"What is network sniffing?",back:"Capturing and analyzing packets on a network. Legitimate use: debugging. Malicious use: stealing unencrypted data."},
  {id:396,bi:4,front:"What is ARP spoofing?",back:"Sending fake ARP messages linking attacker's MAC to a legitimate IP — enables man-in-the-middle attacks on a LAN."},
  {id:397,bi:4,front:"What is DNS spoofing (cache poisoning)?",back:"Corrupting a DNS cache to redirect domain name lookups to malicious IP addresses."},
  {id:398,bi:4,front:"What is the principle of least privilege?",back:"Users and processes should have only the minimum access needed for their function — limits damage from breaches."},
  {id:399,bi:4,front:"What is defense in depth?",back:"Using multiple layers of security so that if one fails, others still protect the system."},
  {id:400,bi:4,front:"What is security through obscurity?",back:"Relying on secrecy of design rather than real security measures. Considered weak — not a reliable security strategy."},

  // ============================================================
  // BIG IDEA 5: IMPACT OF COMPUTING (IOC) — 100 cards
  // ============================================================
  {id:401,bi:5,front:"What is the Digital Divide?",back:"Unequal access to technology based on income, geography, age, education, disability, or language. Creates opportunity disparities."},
  {id:402,bi:5,front:"What is PII?",back:"Personally Identifiable Information — name, SSN, address, phone, email, biometrics. Must be protected for privacy."},
  {id:403,bi:5,front:"What is Phishing?",back:"Tricking users via fake emails/websites into revealing passwords or financial info by impersonating trusted entities."},
  {id:404,bi:5,front:"What is Crowdsourcing?",back:"Obtaining data, ideas, or services from a large group of people online. Examples: Wikipedia, Waze, reCAPTCHA, Foldit."},
  {id:405,bi:5,front:"What is Creative Commons?",back:"Flexible licensing allowing creators to share with specific conditions (attribution, non-commercial, share-alike)."},
  {id:406,bi:5,front:"What is Algorithmic Bias?",back:"When algorithms produce systematically unfair results due to biased training data or design. Can discriminate in hiring, lending, justice."},
  {id:407,bi:5,front:"What is Open Source Software?",back:"Software with freely available source code for anyone to view, use, modify, distribute. Examples: Linux, Firefox, Python."},
  {id:408,bi:5,front:"What is Net Neutrality?",back:"The principle that ISPs treat all internet traffic equally, not prioritizing or blocking content based on source or type."},
  {id:409,bi:5,front:"What is copyright?",back:"Automatic legal protection for original creative works. Others cannot reproduce, distribute, or modify without permission."},
  {id:410,bi:5,front:"What is a patent?",back:"Legal protection for inventions granting exclusive rights to use/sell for a limited time (typically 20 years)."},
  {id:411,bi:5,front:"What is a trademark?",back:"Legal protection for brand identifiers (logos, names, slogans) that distinguish one company's products from another's."},
  {id:412,bi:5,front:"What is fair use?",back:"Allows limited use of copyrighted material without permission for purposes like education, commentary, parody, research."},
  {id:413,bi:5,front:"What is the Digital Millennium Copyright Act (DMCA)?",back:"US law protecting copyrights in the digital age. Criminalizes circumventing digital copy protection and ISP safe harbors."},
  {id:414,bi:5,front:"What is intellectual property?",back:"Creations of the mind (inventions, artistic works, designs, symbols) protected by copyright, patents, or trademarks."},
  {id:415,bi:5,front:"What is a Creative Commons 'BY' license?",back:"Attribution required — you can use/share/modify the work if you credit the original creator."},
  {id:416,bi:5,front:"What is a Creative Commons 'NC' license?",back:"Non-Commercial — you can use the work but not for commercial purposes."},
  {id:417,bi:5,front:"What is a Creative Commons 'SA' license?",back:"ShareAlike — if you modify the work, you must release your version under the same license."},
  {id:418,bi:5,front:"What is a Creative Commons 'ND' license?",back:"NoDerivatives — you can share but not modify the work."},
  {id:419,bi:5,front:"What is the public domain?",back:"Works with no copyright protection — anyone can use freely. Includes very old works and government publications."},
  {id:420,bi:5,front:"What is plagiarism in computing?",back:"Using others' code or ideas without attribution. Even open-source code may require crediting the author."},
  {id:421,bi:5,front:"What is the 'filter bubble'?",back:"When algorithms show users only content matching their interests/views, limiting exposure to diverse perspectives."},
  {id:422,bi:5,front:"What is misinformation?",back:"False information shared without intent to deceive. Often spread virally online due to confirmation bias."},
  {id:423,bi:5,front:"What is disinformation?",back:"Deliberately false information created and spread to deceive people — intentional misinformation."},
  {id:424,bi:5,front:"What is a deepfake?",back:"AI-generated synthetic media showing someone doing or saying something they didn't. Raises serious ethics concerns."},
  {id:425,bi:5,front:"What is the right to be forgotten?",back:"The right to have personal data deleted from online platforms and search engines — stronger in EU (GDPR) than US."},
  {id:426,bi:5,front:"What is GDPR?",back:"General Data Protection Regulation — EU law giving individuals control over their personal data and imposing strict requirements on organizations."},
  {id:427,bi:5,front:"What is COPPA?",back:"Children's Online Privacy Protection Act — US law restricting collection of personal data from children under 13."},
  {id:428,bi:5,front:"What are cookies (web)?",back:"Small data files stored in browsers by websites to remember user preferences, session state, and track behavior."},
  {id:429,bi:5,front:"What is third-party tracking?",back:"Websites using advertising networks and embedded scripts to track your activity across many different websites."},
  {id:430,bi:5,front:"What is browser fingerprinting?",back:"Identifying a user by unique combination of browser settings (fonts, plugins, screen size) without using cookies."},
  {id:431,bi:5,front:"What is location tracking?",back:"Collecting and storing where a device (and its user) has been using GPS, Wi-Fi, cell towers."},
  {id:432,bi:5,front:"What is facial recognition technology?",back:"AI identifying individuals from photos or video. Raises privacy concerns, has bias issues, used in surveillance."},
  {id:433,bi:5,front:"What is surveillance capitalism?",back:"The practice of collecting and selling users' behavioral data as a product — Google and Facebook's business model."},
  {id:434,bi:5,front:"What is a data broker?",back:"A company collecting personal data from many sources and selling profiles to advertisers, employers, or others."},
  {id:435,bi:5,front:"What is the 'right to privacy'?",back:"The right to control personal information. Not absolute — balanced against security, public interest, other rights."},
  {id:436,bi:5,front:"What is the PATRIOT Act's relevance to computing?",back:"US law expanding government surveillance authority post-9/11, allowing access to internet and phone records."},
  {id:437,bi:5,front:"What is whistleblowing in tech?",back:"Disclosing unethical or illegal activities within a company — e.g., Edward Snowden revealing NSA surveillance."},
  {id:438,bi:5,front:"What is e-waste?",back:"Discarded electronic devices containing toxic materials (lead, mercury). Improper disposal pollutes land and water."},
  {id:439,bi:5,front:"What is the carbon footprint of data centers?",back:"Data centers consume approximately 200 terawatt-hours annually — about 1% of global electricity — contributing to climate change."},
  {id:440,bi:5,front:"What is green computing?",back:"Designing, manufacturing, and using computers in environmentally responsible ways — energy efficiency, recycling."},
  {id:441,bi:5,front:"What is automation's impact on jobs?",back:"Automation displaces some jobs (especially repetitive tasks) while creating others (programming, maintenance). Net effect debated."},
  {id:442,bi:5,front:"What is the gig economy?",back:"Work based on short-term contracts rather than permanent jobs, often via apps (Uber, Upwork). Enabled by computing."},
  {id:443,bi:5,front:"What is digital literacy?",back:"The ability to use technology effectively and critically — including evaluating sources, protecting privacy, creating content."},
  {id:444,bi:5,front:"What is the impact of social media on democracy?",back:"Can enable organizing and free speech, but also enables misinformation, polarization, manipulation, and foreign interference."},
  {id:445,bi:5,front:"What is internet censorship?",back:"Governments or ISPs blocking access to websites or online content. Common in authoritarian countries."},
  {id:446,bi:5,front:"What is the Great Firewall of China?",back:"China's internet censorship system blocking many foreign websites (Google, Facebook, Wikipedia) and monitoring citizens."},
  {id:447,bi:5,front:"What is net activism?",back:"Using the internet to organize, petition, and campaign for social/political change."},
  {id:448,bi:5,front:"What is the 'dark pattern' in UX?",back:"Interface design tricks manipulating users into unintended actions (subscribing, sharing data, making purchases)."},
  {id:449,bi:5,front:"What is attention economy?",back:"Tech companies competing for users' attention as a resource, designing apps to maximize time spent and engagement."},
  {id:450,bi:5,front:"What is accessibility in computing?",back:"Designing technology usable by people with disabilities — screen readers, captions, keyboard navigation, contrast ratios."},
  {id:451,bi:5,front:"What is the WCAG?",back:"Web Content Accessibility Guidelines — standards for making websites accessible to people with disabilities."},
  {id:452,bi:5,front:"What is Section 508?",back:"US law requiring federal agencies to make electronic and information technology accessible to people with disabilities."},
  {id:453,bi:5,front:"What is ADA compliance in tech?",back:"Following Americans with Disabilities Act requirements in digital products — ensuring accessibility for disabled users."},
  {id:454,bi:5,front:"What is the impact of GPS on society?",back:"Enabled turn-by-turn navigation, location services, Uber, Pokemon Go, precision agriculture — transformed daily life."},
  {id:455,bi:5,front:"What is telemedicine?",back:"Healthcare delivered via technology — video consultations, remote monitoring, digital prescriptions. Expanded healthcare access."},
  {id:456,bi:5,front:"What is the impact of computing on science?",back:"Enables climate modeling, genomic sequencing, drug discovery, particle physics, space exploration that are otherwise impossible."},
  {id:457,bi:5,front:"What is a CAPTCHA?",back:"Completely Automated Public Turing test to tell Computers and Humans Apart — tests that humans pass easily but bots struggle with."},
  {id:458,bi:5,front:"What is reCAPTCHA as crowdsourcing?",back:"Google's CAPTCHA system digitizes old books/photos by having users transcribe text that computers can't read accurately."},
  {id:459,bi:5,front:"What is citizen science?",back:"Scientific research projects where non-professional members of the public contribute data or analysis."},
  {id:460,bi:5,front:"What is Wikipedia as crowdsourcing?",back:"Millions of volunteers write and maintain encyclopedia articles — the world's largest freely accessible knowledge base."},
  {id:461,bi:5,front:"What is Waze as crowdsourcing?",back:"GPS app using drivers' real-time reports of accidents, traffic, and hazards to give better routing recommendations."},
  {id:462,bi:5,front:"What are the risks of crowdsourcing?",back:"Inaccurate contributions, coordinated manipulation, vandalism, privacy risks, and lack of accountability."},
  {id:463,bi:5,front:"What is the Mechanical Turk?",back:"Amazon's crowdsourcing platform where people complete small tasks (data labeling, surveys) for small payments."},
  {id:464,bi:5,front:"What is data annotation in AI?",back:"Humans labeling data (images, text) to train AI models — much of this is crowdsourced through platforms like Mechanical Turk."},
  {id:465,bi:5,front:"What is the COMPAS algorithm controversy?",back:"A criminal justice risk assessment algorithm found to predict higher recidivism for Black defendants — a case of algorithmic bias."},
  {id:466,bi:5,front:"What is gender bias in AI hiring tools?",back:"Amazon's AI hiring tool penalized resumes mentioning 'women's' organizations because it trained on historically male-dominated hiring data."},
  {id:467,bi:5,front:"What is healthcare AI bias?",back:"Studies found healthcare algorithms underestimated Black patients' needs because spending was used as a proxy for health needs (lower spending due to systemic inequities)."},
  {id:468,bi:5,front:"What is facial recognition bias?",back:"Commercial systems have significantly higher error rates for darker-skinned faces — especially for women with darker skin."},
  {id:469,bi:5,front:"What causes algorithmic bias?",back:"Biased training data reflecting historical inequities, non-diverse development teams, wrong proxy metrics, underrepresentation."},
  {id:470,bi:5,front:"How can algorithmic bias be reduced?",back:"Diverse development teams, representative training data, regular audits, transparency, human oversight, bias testing."},
  {id:471,bi:5,front:"What is explainable AI (XAI)?",back:"AI systems that can explain their decisions in human-understandable terms — important for accountability and bias detection."},
  {id:472,bi:5,front:"What is AI transparency?",back:"Being open about how AI systems work, what data they use, and how they make decisions."},
  {id:473,bi:5,front:"What is algorithmic accountability?",back:"The concept that developers and organizations are responsible for the outcomes and impacts of their algorithms."},
  {id:474,bi:5,front:"What is the 'black box' problem in AI?",back:"Many ML models (especially deep learning) make decisions in ways humans can't easily understand or explain."},
  {id:475,bi:5,front:"What is cyberbullying?",back:"Using digital technology to harass, intimidate, or harm others. Amplified by online anonymity and viral spread."},
  {id:476,bi:5,front:"What is online radicalization?",back:"The process by which people are gradually exposed to increasingly extreme views via recommendation algorithms."},
  {id:477,bi:5,front:"What is the right to be informed about automated decisions?",back:"Under GDPR, individuals have the right to know when automated systems make significant decisions about them and why."},
  {id:478,bi:5,front:"What is responsible computing?",back:"Developing and using technology with awareness of potential harms and a commitment to beneficial, ethical outcomes."},
  {id:479,bi:5,front:"What is the ACM Code of Ethics?",back:"Professional ethical guidelines for computing professionals emphasizing honesty, avoiding harm, respecting privacy, and public welfare."},
  {id:480,bi:5,front:"What is the trolley problem applied to self-driving cars?",back:"If a crash is unavoidable, how should autonomous vehicles choose who to protect? Raises ethics of programming moral decisions."},
  {id:481,bi:5,front:"What is digital identity?",back:"The online representation of a person — accounts, profiles, activity. Can be stolen (identity theft) or manipulated."},
  {id:482,bi:5,front:"What is identity theft?",back:"Using someone's personal information without authorization to commit fraud or other crimes."},
  {id:483,bi:5,front:"What is social media's impact on mental health?",back:"Studies link heavy use to increased anxiety, depression, and loneliness, especially in teenagers. Design choices contribute."},
  {id:484,bi:5,front:"What is the impact of streaming on traditional media?",back:"Netflix, Spotify disrupted TV/music industries, changing how content is created, distributed, and consumed."},
  {id:485,bi:5,front:"What is net neutrality's status in the US?",back:"Has been repealed and reinstated multiple times in the US; ongoing political debate about ISP regulation."},
  {id:486,bi:5,front:"What is digital equity?",back:"Ensuring all individuals have equal access to and skills for technology — addressing the digital divide systematically."},
  {id:487,bi:5,front:"What is computing's impact on criminal justice?",back:"Predictive policing, facial recognition, COMPAS — raise serious concerns about bias, due process, and civil liberties."},
  {id:488,bi:5,front:"What is open data?",back:"Government and institutional data made freely available to the public — enables transparency, research, and new applications."},
  {id:489,bi:5,front:"What is the role of the internet in social movements?",back:"Enables rapid organizing, information sharing, and global solidarity — used in Arab Spring, Black Lives Matter, #MeToo."},
  {id:490,bi:5,front:"What is computing's impact on privacy in public spaces?",back:"Surveillance cameras with facial recognition, license plate readers, and smart city sensors have dramatically reduced anonymity."},
  {id:491,bi:5,front:"What is the Turing Test?",back:"A test of AI intelligence where a machine must fool a human judge into thinking it's human through conversation."},
  {id:492,bi:5,front:"What is strong vs weak AI?",back:"Strong AI: hypothetical human-level general intelligence. Weak AI: AI specialized for specific tasks (current AI)."},
  {id:493,bi:5,front:"What is the impact of AI on creative fields?",back:"AI can generate music, art, text, and code. Raises questions about authorship, copyright, and creative workers' jobs."},
  {id:494,bi:5,front:"What is computing's impact on education?",back:"Online learning, personalized tutoring, instant access to information, collaboration tools have transformed education globally."},
  {id:495,bi:5,front:"What is a digital footprint?",back:"The trail of data left by online activity — browsing history, social posts, purchases. Difficult to erase permanently."},
  {id:496,bi:5,front:"What is informed consent in data collection?",back:"Users should clearly understand what data is collected, how it's used, and must agree voluntarily before data is taken."},
  {id:497,bi:5,front:"What is the principle of data minimization?",back:"Collecting only the minimum data necessary for a specific purpose — a key GDPR principle reducing privacy risks."},
  {id:498,bi:5,front:"What is the ethics of free services vs. data collection?",back:"'If you're not paying, you're the product' — free services often monetize through collecting and selling user data."},
  {id:499,bi:5,front:"What is computing's impact on physical health?",back:"Sedentary behavior from screen time, ergonomic issues, eye strain, sleep disruption from blue light — plus fitness tracking benefits."},
  {id:500,bi:5,front:"What is the future of computing's societal impact?",back:"AI, quantum computing, biotech convergence raises new questions about human identity, labor, privacy, power, and what it means to be human."}
];
